name: Absolute Secret Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    name: Gitleaks 密码嗅探引擎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Gitleaks Action
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Gitleaks是一套开源界公认的黄金标准防御，它会自动阻断试图在 PR 或 Push 里带上 Keys 的代码。